import { env } from "../config/env.js";

export type RpcSource = { chain: string; url: string; type: "evm" | "solana" };
function sources(): RpcSource[] { return env.ONCHAIN_RPC_URLS.split(",").map((x) => x.trim()).filter(Boolean).map((x) => { const [chain, url] = x.split("=", 2); return { chain: chain || "unknown", url: url || "", type: chain?.toLowerCase() === "solana" ? "solana" : "evm" }; }).filter((x) => x.url); }
async function rpc(url: string, method: string, params: unknown[] = []) { const response = await fetch(url, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ jsonrpc: "2.0", id: Date.now(), method, params }), signal: AbortSignal.timeout(env.ONCHAIN_RPC_TIMEOUT_MS) }); if (!response.ok) throw new Error(`RPC HTTP ${response.status}`); const body = await response.json() as { result?: unknown; error?: { message?: string } }; if (body.error) throw new Error(body.error.message || "RPC error"); return body.result; }
export function listOnchainSources() { return sources().map(({ chain, type }) => ({ chain, type })); }
export async function getLatestOnchain() { return Promise.all(sources().map(async (source) => { try { const data = source.type === "solana" ? { slot: await rpc(source.url, "getSlot", [{ commitment: "confirmed" }]), epochInfo: await rpc(source.url, "getEpochInfo", [{ commitment: "confirmed" }]) } : { blockNumber: await rpc(source.url, "eth_blockNumber"), chainId: await rpc(source.url, "eth_chainId"), gasPrice: await rpc(source.url, "eth_gasPrice") }; return { ok: true, chain: source.chain, type: source.type, data }; } catch (error) { return { ok: false, chain: source.chain, type: source.type, error: error instanceof Error ? error.message : "Unknown RPC error" }; } })); }
export async function getEvmBlock(chain: string, tag = "latest") { const source = sources().find((x) => x.type === "evm" && x.chain.toLowerCase() === chain.toLowerCase()); if (!source) throw new Error(`No EVM RPC configured for ${chain}`); return { chain: source.chain, block: await rpc(source.url, "eth_getBlockByNumber", [tag, true]) }; }
export async function getSolanaSlot() { const source = sources().find((x) => x.type === "solana"); if (!source) throw new Error("No Solana RPC configured"); const [slot, epochInfo] = await Promise.all([rpc(source.url, "getSlot", [{ commitment: "confirmed" }]), rpc(source.url, "getEpochInfo", [{ commitment: "confirmed" }])]); return { chain: source.chain, slot, epochInfo }; }
